# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to Develop

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run build --if-present
      # - run: npm test

      - name: Deploy to Dev
        env:
          AWS_REGION: ${{ secrets.RSGIS_WM_WEB_S3_AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.RSGIS_WM_WEB_S3_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.RSGIS_WM_WEB_S3_AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ vars.RSGIS_WM_WEB_S3_BUCKET }}
          AWS_S3_FOLDER: ${{ vars.RSGIS_WM_WEB_S3_FOLDER }}
        run: npm run deploy-develop
